Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using ClientNotifications;
using Hangfire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using pet_manager.BackgroundJob;
using pet_manager.Infrastructure;
using pet_manager.Models;
using pet_manager.Repository;
using pet_manager.ActionFilters;
using static ClientNotifications.Helpers.NotificationHelper;

namespace pet_manager.Controllers
{
    [Authorize]
    public class PetController: Controller
    {
        private IPetRepository _petRepository;
        private UserManager<Owner> _userManager;
        private IUpdatePetRepository _updatePetRepository;
        private IWatchlistRepository _watchlistRepository;
        private INotificationRepository _notificationRepository;
        private IHubContext<SignalServer> _hubContext;
        private IClientNotification _clientNotification;

        public PetController(IPetRepository petRepository,
                            UserManager<Owner> userManager,
                            IUpdatePetRepository updatePetRepository,
                            IWatchlistRepository watchlistRepository,
                            INotificationRepository notificationRepository,
                            IHubContext<SignalServer> hubContext,
                            IClientNotification clientNotification)
        {
            _petRepository = petRepository;
            _userManager = userManager;
            _updatePetRepository = updatePetRepository;
            _watchlistRepository = watchlistRepository;
            _notificationRepository = notificationRepository;
            _hubContext = hubContext;
            _clientNotification = clientNotification;
        }
        
        [TypeFilter(typeof(UserLogAttribute),Arguments = new Object[]{"From Index Action"})]
        public IActionResult Index(){
            return View(_petRepository.GetAllPets());
        }

        public IActionResult GetSellingPets(){
            return View("_PetList",_petRepository.GetSellingPets());
        }
        public IActionResult Detail(int Id, int notificationId=0){
            List<History> histories = _petRepository.GetPetWithHistories(Id);
            ViewBag.histories = histories;

            if(notificationId>0)
                _notificationRepository.UpdateNotificationReadStatusToTrue(notificationId);
            
            return View(_petRepository.GetPet(Id));
        }

        public IActionResult New(){
            return View(new Pet());
        }

        [HttpPost]
        [ModelValidator]
        [TypeFilter(typeof(UserLogAttribute),Arguments = new Object[]{"Pet Creation"})]
        
        public IActionResult New(Pet pet){
            try{
                pet.OwnerId = _userManager.GetUserId(HttpContext.User);

                if(TempData["fileName"]!=null){
                    pet.ImageUrl = TempData["fileName"].ToString();
                }

                _petRepository.Save(pet);

                TempData["fileName"]="";

                _clientNotification.AddSweetNotification("Success","Your pet was added!",NotificationType.success);

            } catch (Exception ex){
                _clientNotification.AddSweetNotification("Error","Your pet was not added!",NotificationType.error);
                
            }
            return RedirectToAction("MyPets","Home");
        }

        [TypeFilter(typeof(UserLogAttribute),Arguments = new Object[] {"Delete Action of Pet controller"})]
        public IActionResult Delete(int Id){
            try{
                _petRepository.Delete(_petRepository.GetPet(Id));
                _clientNotification.AddSweetNotification("Success","Pet Deleted",NotificationType.success);
                return Ok();
            } catch (Exception ex){
                _clientNotification.AddSweetNotification("Could not delete pet. Please try again!","",NotificationType.error);                
                return BadRequest();
            }
        }

        public IActionResult UploadImage(IFormFile file){
            if(file==null || file.Length==0)
                return Content("File not selected");
            if(!file.ContentType.Equals("image/png")){
                return Content("Invalid file type. Try again!");
            }

            TempData["fileName"] = new FileUploader().Upload(file);
            return Ok("Success");
        }

        public IActionResult ToggleToSellingList(int Id){
            Pet pet = _petRepository.GetPet(Id);

            if(!pet.OwnerId.Equals(_userManager.GetUserId(HttpContext.User)))
                return Content("You are not authorized for this action");

            pet.IsSelling = !pet.IsSelling;
            _petRepository.Update(pet);

            //Send notification to users who has kept this pet on their watchlists
            if(pet.IsSelling){
                var createNotification = new CreateNotifications(_watchlistRepository,
                                                    _notificationRepository,
                                                    _hubContext);
                // Hangfire
                //     .BackgroundJob
                //     .Enqueue(()=>createNotification
                //     .CreateNotification(Id));
            }

            return RedirectToAction(nameof(Detail),new{Id=Id});
        }

        public IActionResult BuyPet(int Id){
            ViewBag.Id=Id;

            var userId = _userManager.GetUserId(HttpContext.User);

            var pet = new Pet().LockPetForBuying(_petRepository.GetPet(Id),userId);
            
            _petRepository.Update(pet);

            //Schedule to cancel buy after 3 hours if buying does not succeed
            
            UpdatePet update = new UpdatePet(_updatePetRepository);
            string jobId = update.Update(pet);
            TempData["jobId"]=jobId;

            return View();
        }

        public async Task<IActionResult> ConfirmBuying(int Id){
            var pet = _petRepository.GetPet(Id);
    
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if(user!=null){
                var email = user.Email;
                var userId = user.Id;
                
                Hangfire
                .BackgroundJob
                .Enqueue(()=>MailSender.SendMail(pet.Owner.Email,email,Id,userId)); 
            }

            return Content("Request email was successfully sent to owner!");
        }

        public IActionResult ConfirmSelling(int Id, string userId){
            var pet = new Pet().ChangeOwnership(_petRepository.GetPet(Id),userId);
            
            UpdatePet update = new UpdatePet(_updatePetRepository);

            if(TempData["jobId"]!=null)
                update.CancleJob(TempData["jobId"].ToString());
            
            TempData.Clear();

            _petRepository.UpdateWithHistory(pet);
            
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/WatchlistController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using pet_manager.Models;
using pet_manager.Repository;

namespace pet_manager.Controllers{
    
    [Authorize]
    public class WatchlistController:Controller
    {
        private IWatchlistRepository _repository;
        private UserManager<Owner> _userManager;
        private INotificationRepository _notificationRepository;

        public WatchlistController(IWatchlistRepository repository, 
                                    UserManager<Owner> userManager,
                                    INotificationRepository notificationRepository)
        {
            _repository = repository;
            _userManager = userManager;
            _notificationRepository=notificationRepository;
        }

        public IActionResult Index(){
            string UserId = _userManager.GetUserId(HttpContext.User);

            try{
                return View(_repository.GetWatchlists(UserId));
            } catch (Exception ex){
                throw ex;
            }
        }

        public IActionResult New(int petId){
            try{
                string UserId = _userManager.GetUserId(HttpContext.User);

                Watchlist watchlist = new Watchlist();
                watchlist.PetId = petId;

                watchlist.UserId = UserId;

                if(!_repository.IsWatchlistExists(petId,UserId)){
                    _repository.Save(watchlist);
                } else {
                    return Content("Already exists in your watchlists");
                }
                return RedirectToAction(nameof(Index));
            } catch(Exception ex){
                throw ex;
            }
        }

        public IActionResult Remove(int Id){
            if(Id==0){
                return Content("Invalid request");
            }

            try{
                _repository.Remove(_repository.GetWatchlist(Id));
                return RedirectToAction(nameof(Index));
            } catch(Exception ex){
                throw ex;
            }
        }
    }
}

Views/Shared/_DisplayNotifications.cshtml
@model List<Notification>

@foreach(Notification nt in Model){
    <p class="text-white"><a asp-action="Detail" 
            asp-controller="Pet" 
            asp-route-Id="@nt.PetId"
            asp-route-notificationId="@nt.Id">
                @nt.NotificationText
        </a>
        <hr>
    </p>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Pet Manager</title>

    <environment include="Development">
        <!-- <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" /> -->
        <link rel="stylesheet" href="~/vendor/bootswatch/superhero/bootstrap.css" />
        <link rel="stylesheet" href="~/vendor/font-awesome/css/font-awesome.css" />        
        <link rel="stylesheet" href="~/vendor/toastr/build/toastr.css" />  
        <link rel="stylesheet" href="~/vendor/bootstrap-sweetalert/dist/sweetalert.css"/>      
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/vendor/toastr/build/toastr.min.css" />  
        <link rel="stylesheet" href="~/vendor/bootstrap-sweetalert/dist/sweetalert.css"/>                            
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />        
    </environment> 
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Pet Manager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">All Pets</a></li>
                    <li><a asp-area="" asp-controller="Pet" asp-action="GetSellingPets">Selling Pets</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @await Html.PartialAsync("_PrivateMenuPartial")
        @await Component.InvokeAsync("ClientNotifications.Notify")

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Pet Manager</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/vendor/aspnet/signalr-client/dist/browser/signalr-client-1.0.0-alpha2-final.js"></script>
        <script src="~/vendor/toastr/toastr.js"></script> 
        <script src="~/vendor/bootstrap-sweetalert/dist/sweetalert.js"></script> 
         
        <script src="~/js/delete.js" asp-append-version="true"></script>        
        <script src="~/js/site.js" asp-append-version="true"></script>
        
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/vendor/toastr/toastr.js"></script>  
        <script src="~/vendor/bootstrap-sweetalert/dist/sweetalert.min.js"></script> 
        
        <script src="~/vendor/aspnet/signalr-client/dist/browser/signalr-client-1.0.0-alpha2-final.js"></script>
        
        <script src="~/js/delete.js" asp-append-version="true"></script>                
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_PetList.cshtml
@model List<Pet>
    
<hr>
<div class="row">
    @{
        if(Model.Count<=0){
            <p>No pets found</p>
        } else {
            foreach(Pet p in Model){
                <div class="col-md-3">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            @p.Name
                        </div>
                        <div class="panel-body">
                            <div class="col-md-8 image-container">
                                <div class="btn btn-success image-button">
                                    <img class = "image" src="~/images/@p.ImageUrl" onError="event.preventDefault(); this.src='/images/cat.png';"/>                                    
                                </div>
                            </div>
                            <div class="col-md-4">
                                Age: @p.Age
                            </div>
                        </div>
                        <div class="panel-footer">
                            <a asp-action="Detail" 
                                asp-controller="Pet" 
                                asp-route-Id="@p.Id" 
                                class="btn btn-primary">
                                Details
                            </a>
                            <a asp-action="New" 
                                asp-controller="Watchlist" 
                                asp-route-petId="@p.Id" 
                                class="btn btn-primary">
                                Add To Watchlist
                            </a>
                        </div>
                    </div>
                </div>
            }
        }
    }
    </div>

Views/Shared/_PrivateMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using pet_manager.Models

@inject SignInManager<Owner> SignInManager
@inject UserManager<Owner> UserManager

@if(SignInManager.IsSignedIn(User)){
    <div class="row">
        <a class="btn btn-success pull-right add-pet"
            asp-action="Index"
            asp-controller="Watchlist">
            View my watchlists
            <i class="fa fa-circle-add"></i>
        </a>

        <a class="btn btn-primary pull-right add-pet"
            asp-action="New"
            asp-controller="Pet">
            Add new pet
            <i class="fa fa-circle-add"></i>
        </a>
    </div>
} else {
    <div class="row">
        <h2>Welcome to the world of pets!. Please register/login to add your pet.</h2>
    </div>
}

Views/Shared/_UserPrivateMenu.cshtml
@using Microsoft.AspNetCore.Identity
@using pet_manager.Models

@inject SignInManager<Owner> SignInManager
@inject UserManager<Owner> UserManager

@if(UserManager.GetUserId(User).Equals(Model.OwnerId)){
    @if(Model.IsSelling){
        <p>Your pet is in selling list.</p>
        <a class="btn btn-danger"
            asp-action="ToggleToSellingList"
            asp-controller="Pet"
            asp-route-Id="@Model.Id">
            Remove from selling list
        </a>
    } else {
        <a class="btn btn-success"
            asp-action="ToggleToSellingList"
            asp-controller="Pet"
            asp-route-Id="@Model.Id">
            Add to selling list
        </a>
    }

    <a class="btn btn-danger delete" data-controller="Pet" 
                                            data-action="Delete" 
                                            data-Id="@Model.Id"
                                            data-body-message="Are you sure to delete @Model.Name ?"
                                            data-redirect-url="/home/mypets">Delete Pet</a> 
}
@if(!UserManager.GetUserId(User).Equals(Model.OwnerId)){
    if(Model.IsSelling && !Model.IsLocked){
       <a class="btn btn-info"
            asp-action="BuyPet"
            asp-controller="Pet"
            asp-route-Id="@Model.Id">
            Buy
        </a> 
    } 
    
    @if(Model.IsLocked){
        <p>This pet is in buying process by someone. Please come later again to check if it is available.</p>
    }
}

@if(UserManager.GetUserId(User).Equals(Model.LockedByUserId)){
    @if(Model.IsLocked){
        <a class="btn btn-info"
            asp-action="BuyPet"
            asp-controller="Pet"
            asp-route-Id="@Model.Id">
            Confirm Buying
        </a> 
    }
}